apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-bitnami
  namespace: myapp
spec:
  project: default
  source:
    chart: mysql
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: HEAD
    helm:
      releaseName: mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
