apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
spec:
  project: test-project
  source:
    repoURL: https://github.com/my-org/my-app.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true